name = "NPUZ"
uuid = "0edb0d52-f4b3-4ee2-b48e-a3f96d5976ca"
authors = ["bk <brice@allenic.co> and contributors"]
version = "0.1.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
DataStructures = "0.18"
